name: ldm
# This file is part of stable-diffusion-webui (https://github.com/sd-webui/stable-diffusion-webui/).

# Copyright 2022 sd-webui team.
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
channels:
  - pytorch
  - defaults
  - nvidia
# Psst. If you change a dependency, make sure it's mirrored in the docker requirement
# files as well.
dependencies:
  - cuda-toolkit=11.7
  - git
  - numpy=1.23.3
  - pip=20.3
  - python=3.8.5
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - scikit-image=0.19.2
  - torchvision=0.14.0
  - loguru
  - requests
  - pip:
      - -r file:requirements.txt
