name: AI Horde worker new release

on:
  push:
    branches:
      - cicd

jobs:
  build-n-publish:
    name: AI Horde Worker new release
    runs-on: ubuntu-latest
    steps:
    - name: "‚úîÔ∏è Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: "üì£ Release on push"
      id: release
      uses: rymndhng/release-on-push-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        bump_version_scheme: patch
        use_github_release_notes: true
    - name: "‚úèÔ∏è Generate release changelog"
      # if: ${{ steps.release.outputs.version != '' }}
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: "üíæ Commit new version"
      # if: ${{ steps.release.outputs.version != '' }}
      run: |
          version=${{ steps.release.outputs.version }}
          major=$(echo ${version#v} | cut -d '.' -f 1)
          minor=$(echo ${version} | cut -d '.' -f 2)
          patch=$(echo ${version} | cut -d '.' -f 3)

          echo "version=$version"
          echo "major=$major"
          echo "minor=$minor"
          echo "patch=$patch"      
          sed -i "s/^BRIDGE_VERSION = .*/BRIDGE_VERSION = ${major}/g" ./worker/consts.py
          sed -i "s/^RELEASE = f\"{BRIDGE_VERSION}.*\"/RELEASE = f\"{BRIDGE_VERSION}.${minor}.${patch}\"/g" ./worker/consts.py
          head -5 ./worker/consts.py
    #       sed -i 's/version = .*/version = "${{ steps.release.outputs.version }}"/g' ./setup.cfg
    #       sed -i 's/version=".*"/version="${{ steps.release.outputs.version }}"/g' ./setup.py
    #       git config user.email github-actions@github.com
    #       git config user.name github-actions
    #       git commit -am 'version incremented'
    #       git push
    # - name: "Inform with Discord Webhook"
    #   if: ${{ steps.release.outputs.version != '' }}
    #   uses: tsickert/discord-webhook@v5.3.0
    #   with:
    #     webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
    #     content: "New version of nataili has been published to pypi: ${{ steps.release.outputs.version }}"